### PR TITLE
updated gatsby 2.25.0

### PR DESCRIPTION
**Pull request by teru-mi**
Firebase build error. So I updated Gatsby. 

```
 ERROR #11329 

Your plugins must export known APIs from their gatsby-node.js.

See https://www.gatsbyjs.org/docs/node-apis/ for the list of Gatsby node APIs.

- The plugin gatsby-source-filesystem@2.11.1 is using the API "pluginOptionsSchema" which was introduced in gatsby@2.25.0.
- The plugin gatsby-source-filesystem@2.11.1 is using the API "pluginOptionsSchema" which was introduced in gatsby@2.25.0.
- The plugin gatsby-transformer-sharp@2.12.1 is using the API "unstable_shouldOnCreateNode" which was introduced in gatsby@2.24.80.
- The plugin gatsby-plugin-sharp@4.1.0 is using the API "pluginOptionsSchema" which was introduced in gatsby@2.25.0.
- The plugin gatsby-plugin-manifest@4.1.0 is using the API "pluginOptionsSchema" which was introduced in gatsby@2.25.0.

Some of the following may help fix the error(s):

- npm install gatsby@^2.25.0
- Rename "unstable_shouldOnCreateNode" -> "onCreateNode"

```

### CODE REVIEW

**Review by ssagli — APPROVED** [review]
Should we eventually update all of dependencies here? @kwa-z
the latest Gatsby version is already v4 so maybe upgrade it to v3 next?

**Comment by kwa-z** [comment]
For a blog, its not as important.

**Comment by teru-mi** [comment]
I got Firebase deploy error again. 
It says`error gatsby-plugin-manifest@4.1.0: The engine "node" is incompatible with this module. Expected version ">=14.15.0". Got "12.22.7"`, but it's v15.8.0 when I check `nvm ls`. Should I update node to the latest one? @ssagli

**Comment by kwa-z** [comment]
Are you deploying locally or on GitHub?

**Comment by teru-mi** [comment]
On GitHub @kwa-z

**Comment by kwa-z** [comment]
Should remove the node restriction then.

**Pull request merged**
